[package]
name = "ezo_rtd"
version = "0.1.4"
authors = ["Joaquín R <globojorro@gmail.com>"]

[dependencies]
chrono = "0.4"
ezo_common = { git = "https://github.com/saibatizoku/ezo-common-rs.git", branch = "master" }
failure = "0.1"
i2cdev = "0.4"

[profile.release]
lto = true
